language: go
os:
  - linux
  - osx

sudo: false

# Deploy executables to Github release tags
deploy:
  provider: releases
  api_key:
    secure: VbC70j1oB3fjRdb36CrffO69DmkTK9t/yWzXM9wP7wsMPhlXnat0n/CSqNqY8MDMIeM68ra5iF3sfWmNdQ2yNKq/9Qb9pV0+X68HxhJKmI5LONd8qHqdZzoNa/ITaHHZ3Fyj8KTMMGBTA7ONBJ+DgzIhUcWWsbGNfDkICW7es1d2/8Q/2QhIiZNLfDuWG1V2Af1452ek2YpnOCE3ENvBQ9FYCd4Iv0Y/FGzls3oepoVZPW9bXvX3sceAENNJiAmsnKqlwQW+jho3jv3//64YfaNb1IlU13n85t8HwYUD3v8BriuPEFWwfUft01nNjMV2jwVAlZ9or1Ye/BMh/JCuLNZlrsRQVQ9Etjuaq5NhAWGZXce9wMNQOdxge4rIX/LMddM5ImeBh2lT/UT78gOBlGlPZ9yA6jqEroU9mSw2lLmzW1+sN2XbyUSJw/EMW1mS8DCltkFht1L0XXg/vsgnA+4Z3/9k62OrM/pAtm/TN2vmI1KgNh94PPxCSU1n6iWpA43Mya+8qfRiTecPOVsKzLoIFQegIg1oJ0xoZHlibD88rZz4ZieVhPtMWRjUEY4jJ/PsaI//bwLKhw3LpDgHTNez6ZLIky00VVs7HVIQzMUE8G6zXKUye2+jLduvQyf7g4SacEhJdrOIHdNImsEv88sAWWXmqryd9jZzDLys7L0=
  file: "secretary-$(uname -s)-$(uname -m)"
  skip_cleanup: true
  on:
    tags: true
